// src/components/publications/Publication.svelte
<script lang="ts">
  import type { ResearchProject } from "../../types";
  import LinkItem from "../LinkItem.svelte";
  import Author from "./Author.svelte";

  export let publication: ResearchProject;
</script>

<div class="publication-container">
  <img src={publication.imageSrc} alt={publication.title} />
  <div class="publication-content-container">
    <h3>
      {publication.title} ({publication.venue}, {publication.year})
    </h3>
    <div class="author-container">
      {#each publication.authors as author, index}
        <Author
          {author}
          last={publication.authors.length === index + 1}
          length={publication.authors.length}
        />
      {/each}
    </div>
    <div class="link-item-container">
      {#each publication.links as link}
        <div class="link-item">
          <LinkItem linkWithIcon={link} />
        </div>
      {/each}
    </div>
    <p>{publication.abstract}</p>
  </div>
</div>

<style lang="scss">
  .publication-container {
    display: flex;
    padding-bottom: 2em;
  }

  @media (max-width: 800px) {
    .publication-container {
      display: flex;
      flex-direction: column;
      padding-bottom: 4em;
    }

    h3 {
      padding-top: 5px;
    }
  }

  @media (min-width: 800px) {
    img {
      height: 100%;
    }
  }

  .publication-content-container {
    display: flex;
    flex-direction: column;
  }

  .author-container {
    display: flex;
    flex-wrap: wrap;
    flex: 1 1 auto;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
  }

  img {
    object-fit: cover;
    max-width: 250px;
    margin-right: 1em;
  }

  .link-item {
    margin-right: 5px;
  }

  .link-item-container {
    display: flex;
  }
</style>

// src/views/projects/publications/Publication.vue
<template>
  <v-container>
    <v-row class="negative-row">
      <v-col md="auto" cols="12" xs="12">
        <img :src="project.imageSRC" alt="Project Image" />
      </v-col>
      <v-col>
        <h3>{{ project.title }} ({{ project.venue }}, {{ project.year }})</h3>
        <v-row class="neutral-row">
          <Author
            v-for="(author, index) in project.authors"
            :key="author"
            :name="author"
            :last="project.authors.length === index + 1"
            :length="project.authors.length"
          />
        </v-row>
        <v-row class="negative-row">
          <LinkItem
            v-for="link in project.links"
            :key="link.link"
            :linkWithIcon="link"
          />
        </v-row>
        <p class="abstract-container">
          {{ project.abstract }}
        </p>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import LinkItem from '../LinkItem.vue';
import Author from './Author.vue';

export default {
  name: 'Publication',

  components: {
    LinkItem,
    Author,
  },
  props: {
    project: Object,
  },
};
</script>

<style lang="scss" scoped>
img {
  width: 100%;
  max-width: 250px;
}
p {
  margin: 0 !important;
}
.negative-row {
  margin-left: -8px;
}
.neutral-row {
  margin-left: 0px;
  margin-top: 5px;
}
.abstract-container {
  margin-top: 12px !important;
}
</style>
