// src/components/head/Navigation.svelte
<script lang="ts">
  import slocation from "slocation";

  export let picHeight;
  export let windowWidth;

  $: pathname = $slocation.pathname;

  function setPathname(path: string) {
    pathname = path;
  }
</script>

<div class="navigation-container">
  <div
    class="navigation-before"
    style="width: {(windowWidth - picHeight) / 2}px;"
  >
    <a
      href="/publications"
      on:click={() => setPathname("/publications")}
      class="navigation-link {pathname === '/publications' ? 'active' : ''}"
      >Papers</a
    >
    <a
      href="/research"
      on:click={() => setPathname("/research")}
      class="navigation-link {pathname === '/research' ? 'active' : ''}"
      >Research</a
    >
  </div>
  <div
    class="avatar-container"
    style="width: {picHeight}px; height: {picHeight}px;"
  >
    <a href="/" on:click={() => setPathname("/")}>
      <img
        class="avatar"
        style="width: {picHeight}px; height: {picHeight}px;"
        src="images/alex_small.jpg"
        alt="Profile image Alex Bäuerle"
      />
    </a>
  </div>
  <div
    class="navigation-after"
    style="width: {(windowWidth - picHeight) / 2}px;"
  >
    <a
      href="/projects"
      on:click={() => setPathname("/projects")}
      class="navigation-link {pathname === '/projects' ? 'active' : ''}"
      >Projects</a
    >
    <a
      href="/cv"
      on:click={() => setPathname("/cv")}
      class="navigation-link {pathname === '/cv' ? 'active' : ''}">CV</a
    >
  </div>
</div>

<style lang="scss">
  .avatar {
    border-radius: 50%;
  }

  .avatar-container {
    padding-top: 12px;
    padding-bottom: 12px;
  }

  .navigation-container {
    display: flex;
    align-items: center;
    flex-wrap: nowrap;
    justify-content: center;
  }

  .navigation-link {
    padding: 10px;
    font-size: 16pt;
    color: #2c3e50;
    text-decoration: underline;

    &:active {
      color: rgb(67, 151, 236);
    }
  }

  .navigation-before {
    margin-right: 20px;
    display: flex;
    flex-wrap: wrap;
    align-items: flex-end;
    justify-content: flex-end;
  }

  .navigation-after {
    margin-left: 20px;
    display: flex;
    flex-wrap: wrap;
    align-items: flex-start;
    justify-content: flex-start;
  }

  .active {
    color: rgb(67, 151, 236);
  }
</style>

// src/views/head/Navigation.vue
<template>
  <v-row align="center" justify="center" class="no-wrap">
    <v-col>
      <v-row align="end" justify="end">
        <v-col class="non-growing">
          <router-link to="/publications">Papers</router-link>
        </v-col>
        <v-col class="non-growing">
          <router-link to="/research">Research</router-link>
        </v-col>
      </v-row>
    </v-col>
    <v-col cols="2" class="avatar-container">
      <router-link to="/">
        <v-avatar size="100%" max-width="150" min-width="0%">
          <img
            src="@/assets/alex_small.jpg"
            alt="Profile image Alex Bäuerle"
            ref="pic"
          />
        </v-avatar>
      </router-link>
    </v-col>
    <v-col>
      <v-row align="end" justify="begin">
        <v-col class="non-growing">
          <router-link to="/fun">Projects</router-link>
        </v-col>
        <v-col class="non-growing">
          <a :href="getBaseURL() + '/CV_Alex_Baeuerle.pdf'" target="_blank">
            CV
          </a>
        </v-col>
      </v-row>
    </v-col>
  </v-row>
</template>

<script>
export default {
  name: 'Navigation',

  methods: {
    getPicHeight() {
      const windowShare = (window.innerWidth / 12) * 2;
      const picHeight = Math.max(Math.min(150, windowShare), 130);
      this.$store.commit('setHeadHeight', picHeight + 84);
    },
    getBaseURL() {
      return window.location.origin;
    },
  },
  created() {
    window.addEventListener('resize', this.getPicHeight);
    this.getPicHeight();
  },
};
</script>

<style lang="scss">
a {
  font-size: 16pt;
  color: #2c3e50 !important;

  &.router-link-exact-active {
    color: rgb(67, 151, 236) !important;
  }
}
.avatar-container {
  min-width: 130px;
}

.non-growing {
  flex-grow: 0;
  white-space: nowrap;
}

.no-wrap {
  flex-wrap: nowrap;
}
</style>
