// src/views/research/Workplace.vue
<template>
  <v-container>
    <v-row>
      <v-col>
        <v-icon color="black">{{workplace.icon}}</v-icon>
        <h3>
          {{ workplace.title }} ({{ workplace.timeframe }})
        </h3>
        <p>
          {{ workplace.abstract }}
        </p>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>

export default {
  name: 'Workplace',
  props: {
    workplace: Object,
    id: Number,
  },
};
</script>

<style lang="scss" scoped>
img {
  width: 100%;
  max-width: 250px;
}
p {
  margin: 0 !important;
}
</style>

// src/components/cv/Workplace.svelte
<script lang="ts">
  import type { Work } from "../../types";

  export let employment: Work;

  let props = { size: "1.5em" };
</script>

<div class="work-element-container">
  <div class="title-container">
    <div class="icon">
      <svelte:component this={employment.icon} {...props} />
    </div>
    <h3>
      {employment.title}
    </h3>
  </div>
  <p class="timeframe">
    {employment.timeframe}
  </p>
  <p>
    {employment.abstract}
  </p>
</div>

<style lang="scss">
  .work-element-container {
    padding-bottom: 1em;
    position: relative;
  }

  @media (min-width: 800px) {
    .timeframe {
      position: absolute;
      top: 0px;
      right: 0px;
    }
  }

  .icon {
    margin-bottom: -5px;
    margin-right: 5px;
  }

  .title-container {
    display: flex;
  }

  h3 {
    max-width: 600px;
  }
</style>
