// src/views/research/Talk.vue
<template>
  <v-container>
    <v-row>
      <v-col>
        <h3>{{ project.title }}</h3>
        <v-row class="neutral-row">
          {{ project.venue }}, {{ project.date.toDateString() }}
          <LinkItem
            v-for="link in project.links"
            :key="link.link"
            :linkWithIcon="link"
          />
        </v-row>
        <v-row>
        </v-row>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import LinkItem from '../projects/LinkItem.vue';

export default {
  name: 'Talk',

  components: {
    LinkItem,
  },
  props: {
    project: Object,
  },
};
</script>

<style lang="scss" scoped>
p {
  margin: 0 !important;
}
.neutral-row {
  margin-left: 0px;
  margin-top: 5px;
  align-items: center;
}
</style>

// src/components/research/Talk.svelte
<script lang="ts">
  import type { Talk } from "../../types";
  import LinkItem from "../LinkItem.svelte";

  export let talk: Talk;
</script>

<div class="talk-container">
  <h3>
    {talk.title}
  </h3>
  <div class="talk-details-container">
    <p>
      {talk.venue}, ({talk.date.toDateString()})
    </p>
    <div class="link-item-container">
      {#each talk.links as link}
        <LinkItem linkWithIcon={link} />
      {/each}
    </div>
  </div>
</div>

<style lang="scss">
  .talk-container {
    padding-bottom: 1em;
    display: flex;
    flex-direction: column;
  }
  .talk-details-container {
    display: flex;
    align-items: center;
    flex-wrap: wrap;
  }

  p {
    margin-right: 5px;
  }

  .link-item-container {
    margin-bottom: -5px;
  }
</style>
