// src/views/research/Workplace.vue
<template>
  <v-container>
    <v-row>
      <v-col>
        <v-icon color="black">{{workplace.icon}}</v-icon>
        <h3>
          {{ workplace.title }} ({{ workplace.timeframe }})
        </h3>
        <p>
          {{ workplace.abstract }}
        </p>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>

export default {
  name: 'Workplace',
  props: {
    workplace: Object,
    id: Number,
  },
};
</script>

<style lang="scss" scoped>
img {
  width: 100%;
  max-width: 250px;
}
p {
  margin: 0 !important;
}
</style>

// src/components/research/Workplace.svelte
<script lang="ts">
  import type { Work } from "../../types";

  export let employment: Work;

  let props = { size: "1.5em" };
</script>

<div class="workplace-container">
  <svelte:component this={employment.icon} {...props} />
  <h3>{employment.title} ({employment.timeframe})</h3>
  <p>{employment.abstract}</p>
</div>

<style lang="scss">
  .workplace-container {
    padding-bottom: 1em;
  }
</style>
